services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - HASKELL_SERVICE_URL=http://haskell-service:8081/field-stats
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    depends_on:
      - haskell-service

  haskell-service:
    build: ./haskell-service
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smartcrop_frontend

    ports:
      - "3000:80"

    environment:
      - VITE_API_URL=http://backend:8000

    depends_on:
      - backend

    restart: unless-stopped
