services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - HASKELL_SERVICE_URL=http://haskell-service:8081/field-stats
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./backend/data:/app/data

    depends_on:
      - haskell-service

  haskell-service:
    build: ./haskell-service
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://46.225.7.134:8000
        - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
    container_name: smartcrop_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
