name:                haskell-service
version:             0.1.10.0

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - aeson
  - text
  - http-types
  - wai-extra

library:
  source-dirs: src
  exposed-modules:
    - Stats

executables:
  haskell-service-exe:
    main:                Main.hs
    source-dirs:         src
    dependencies:
      - haskell-service