name: Deploy to Server

on:
  push:
    branches:
      - master

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: http://46.225.7.134
          environment: production
          initial-status: in_progress

      - name: SSH and Update Docker
        uses: appleboy/ssh-action@master
        with:
          host: 46.225.7.134
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/SmartCropMonitor
            git fetch origin master
            git reset --hard origin/master
            docker compose up -d --build

      - name: Update Deployment Status (Success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          environment-url: http://46.225.7.134
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update Deployment Status (Failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
